import type { NextPage, GetStaticProps } from 'next';
import Layout from '../components/layout/Layout';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import Hero from '../components/sections/Hero';
import AboutMe from '../components/sections/AboutMe';
import { AboutMeProps } from '../interfaces/AboutMeProps';

type Props = {
  aboutMe: AboutMeProps[];
  homeHero: AboutMeProps[];
};

const Home = ({ aboutMe, homeHero }: Props) => {
  const heroImg = homeHero[0].image[0].fields;
  const heroText = homeHero[0].item.fields;
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Wood-Ridge Dems</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Hero imgLink={`https:${heroImg.file.url}`}>
            <h1>{heroText.title}</h1>
            <h2>{heroText.subtitle}</h2>
          </Hero>
          <AboutMe data={aboutMe[1]} />
        </main>
      </div>
    </Layout>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await axios(`https://cdn.contentful.com/spaces/nc2tb1hvkxx7/entries?access_token=${process.env.CONTENTFUL_TOKEN}&content_type=aboutMe`);
  const { data } = res;

  const hero = await axios(
    `https://cdn.contentful.com/spaces/nc2tb1hvkxx7/entries?access_token=${process.env.CONTENTFUL_TOKEN}&content_type=homehero`
  );
  const heros = hero.data;

  function getDataNImages(data, fieldname) {
    const newArr = data.items.map((item) => {
      const image_id = item.fields[fieldname].sys.id;
      const image = data.includes.Asset.filter((img) => {
        return img.sys.id === image_id;
      });
      return { item, image };
    });

    return newArr;
  }

  const aboutMeData = getDataNImages(data, 'aboutMeImage');
  const heroData = getDataNImages(heros, 'heroimage');

  return { props: { aboutMe: aboutMeData, homeHero: heroData } };
};
